name: enigmatica 6
on: [push]
jobs:
  expert:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # download server
      - run: wget https://media.forgecdn.net/files/3725/641/Enigmatica6ExpertServer-1.1.2.zip
      - run: ls

      # unzip server
      - run: unzip *.zip
      - run: ls

      # 1st server run
      - uses: actions/setup-node@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: echo "eula=true" >> eula.txt 
      - run: node install-server.js
      - run: ls
